language: node_js
node_js: stable
branches:
  onlyt:
  - source
cache:
  yarn: true
  directories:
  - node_modules
before_install:
- git config --global user.name "EltonChou"
- git config --global user.email "plscd748@gmail.com"
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH=$HOME/.yarn/bin:$PATH
- npm install -g hexo-cli
install:
- yarn
script:
- hexo clean
- hexo generate
after_success:
- cd ./public
- git init
- git add --all .
- git commit -m "Travis CI Auto Builder"
- git push --quiet --force https://$github_token@github.com/EltonChou/EltonChou.github.io.git master 
